spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vieiraadmjohnny@gmail.com
    password: dzaq qexr bxcn wgqt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

envio:
  email:
    remetente: vieiraadmjohnny@gmail.com
    nomeRemetente: "Johnny"

server:
  port: 8082


